project:
  type: website
  output-dir: docs
  
website:
  title: "SEIR-vector Model"
  favicon: images/logo.png
  navbar:
    left:
      - href: overview.qmd
        text: Overview
      - href: diagnostics.qmd
        text: Diagnostics
    right:
      - href: https://geoepi.github.io/
        text: GeoEpi
      - href: https://geoepi.github.io/pindex.html
        text: Research
      - icon: github
        href: https://github.com/geoepi/seir-vector
  page-footer:
    right: "Built with [Quarto](https://quarto.org/)"

format:
  html:
    theme: lux
    toc: true
    
editor: source

