project:
  type: website
  output-dir: docs
  
website:
  title: "SEIR-vector Model"
  navbar:
    left:
      - href: overview.qmd
        text: Overview 
      - workflow.qmd
      - results.qmd
    tools:
      - icon: github
        href: https://github.com/geoepi/
  page-footer:
    right: "Built with [Quarto](https://quarto.org/)"

format:
  html:
    theme: lux
    toc: true
    
editor: source

